version: "3.4"

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: anderson
      POSTGRES_PASSWORD: anderson
      POSTGRES_DB: heroes
    restart: always

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_INITDB_DATABASE
      - DATABASE_USERNAME=$DATABASE_USER
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - MONGO_PORT=$MONGO_PORT
    volumes:
      - ./docker_scripts/:/docker-entrypoint-initdb.d

  mongoClient:
    image: mongoclient/mongoclient
    ports:
      - "3000:3000"
    restart: always
